
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzzqeasoxguvewjmbcrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6enFlYXNveGd1dmV3am1iY3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MzYzNzMsImV4cCI6MjA1OTIxMjM3M30.BbsjWJbQSJH_Xn_-jJRPTC1VKqbsTEVB1nCpSMzIpvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Define the valid permission types
export type PermissionAction = 
  'add_product' | 
  'delete_product' | 
  'edit_product' | 
  'add_price_history' | 
  'delete_price_history' | 
  'edit_price_history';

// Helper function to check if a user has permission for a specific action
export async function checkPermission(action: PermissionAction): Promise<boolean> {
  try {
    const { data: result, error } = await supabase
      .rpc('user_has_permission', { action });

    if (error) {
      console.error('Error checking permission:', error);
      return false;
    }

    return result || false;
  } catch (error) {
    console.error('Error in checkPermission:', error);
    return false;
  }
}
